### ISSUE TITLE
Possible Issue while extracting EDID from Samsung NP530U3C-AB1AR

### ISSUE THREAD

**Issue by cacciaresi** [bulletmark/edid-rw#2]
Hi, first of all thanks for work :)

I'm trying to extract the EDID from my notebook: _NP530U3C-AB1AR_  with _HD4000_ and I see this output:

<pre>
$ sudo ./edid-rw 0 | edid-decode
Traceback (most recent call last):
  File "./edid-rw", line 141, in <module>
    main()
  File "./edid-rw", line 129, in main
    edid = [dev.read(i) for i in range(EDID_HDR)]
  File "./edid-rw", line 48, in read
    return self.smb.read_byte_data(EDID_ADDR, n)
IOError: [Errno 6] No such device or address
Extracted contents:
header:          00 00 00 00 00 00 00 00
serial number:   00 00 00 00 00 00 00 00 00 00
version:         00 00
basic params:    00 00 00 00 00
chroma info:     00 00 00 00 00 00 00 00 00 00
established:     00 00 00
standard:        00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
descriptor 1:    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
descriptor 2:    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
descriptor 3:    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
descriptor 4:    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
extensions:      00
checksum:        00

No header found
Manufacturer: @@@ Model 0 Serial Number 0
EDID version: 0.0
Analog display, Input voltage level: 0.7/0.3 V
Sync: 
Image size is variable
Gamma: 1.00
Monochrome or grayscale display
Established timings supported:
Standard timings supported:
non-conformant standard timing (0 horiz)
non-conformant standard timing (0 horiz)
non-conformant standard timing (0 horiz)
non-conformant standard timing (0 horiz)
non-conformant standard timing (0 horiz)
non-conformant standard timing (0 horiz)
non-conformant standard timing (0 horiz)
non-conformant standard timing (0 horiz)
Manufacturer-specified data, tag 0
Manufacturer-specified data, tag 0
Manufacturer-specified data, tag 0
Manufacturer-specified data, tag 0
Checksum: 0x0
EDID block does not conform at all!
    Bad year of manufacture
    Manufacturer name field contains garbage
</pre>

Please, anything you need from my side (more info from the computer hardware or commands output) don't hesitate to ask me.

**Comment by matteraf** [comment]
Hola cacciaresi, al final lograste hacer andar OSX en la Samsung?
Yo estoy luchando
