### ISSUE TITLE
IOError: [Errno 121] Remote I/O error

### ISSUE THREAD

**Issue by shulhi** [bulletmark/edid-rw#9]
```
$  sudo ./edid-rw 4 | edid-decode
[sudo] password for shulhi: 
Extracted contents:
header:          00 ff ff ff ff ff ff 00
serial number:   06 af 3d 13 00 00 00 00 26 17
version:         01 04
basic params:    95 1f 11 78 02
chroma info:     87 e5 a4 56 50 9e 26 0d 50 54
established:     00 00 00
standard:        01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01
descriptor 1:    14 37 80 b8 70 38 24 40 10 10 3e 00 35 ad 10 00 00 18
descriptor 2:    00 00 00 0f 00 00 00 00 00 00 00 00 00 00 00 00 00 20
descriptor 3:    00 00 00 fe 00 41 55 4f 0a 20 20 20 20 20 20 20 20 20
descriptor 4:    00 00 00 fe 00 42 31 34 30 48 41 4e 30 31 2e 33 20 0a
extensions:      00
checksum:        7a

Manufacturer: AUO Model 133d Serial Number 0
Made week 38 of 2013
EDID version: 1.4
Digital display
6 bits per primary color channel
DisplayPort interface
Maximum image size: 31 cm x 17 cm
Gamma: 2.20
Supported color formats: RGB 4:4:4
First detailed timing is preferred timing
Established timings supported:
Standard timings supported:
Detailed mode: Clock 141.000 MHz, 309 mm x 173 mm
               1920 1936 1952 2104 hborder 0
               1080 1083 1097 1116 vborder 0
               -hsync -vsync 
Manufacturer-specified data, tag 15
ASCII string: AUO
ASCII string: B140HAN01
Checksum: 0x7a (valid)
EDID block does NOT conform to EDID 1.3!
	Missing name descriptor
	Missing monitor ranges
	Detailed block string not properly terminated

$  sudo ./edid-rw -w 4 < LEN.bin
Traceback (most recent call last):
  File "./edid-rw", line 131, in <module>
    main()
  File "./edid-rw", line 115, in main
    dev.write(i, val)
  File "./edid-rw", line 50, in write
    self.smb.write_byte_data(EDID_ADDR, n, val)
IOError: [Errno 121] Remote I/O error
```

I'm running Ubuntu 16.04. Any hints on what is wrong?

**Comment by bulletmark** [comment]
No idea sorry. Have not used this program myself for years.
